on:
  push:
    branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.25.1"

            - name: Build application
              run: go build -o app .

            - name: Build the Docker image
              run: docker build -t veronicalobos/notely:latest .